//! T-33-005 — the ParaLLEl-RDP / Angrylion conformance gate.
//!
//! Each `.rvec` vector under `tests/vectors/` is a golden reference generated by
//! running the **Angrylion** software RDP (the non-commercial study oracle, run
//! externally — see `vectors-gen/README.md` for the license-clean generator) over
//! a fixed RDP command list. The vector carries *only outputs*: the command stream
//! (freely committable) and the golden framebuffer Angrylion rendered — no
//! Angrylion source or binary is vendored, keeping the license boundary clean.
//!
//! This test replays each command stream through RustyN64's own RDP and asserts a
//! byte-for-byte match against the golden framebuffer. Because the command bytes
//! are stored big-endian (RustyN64's RDRAM layout) and the golden pixels are
//! stored as row-major big-endian logical values (which is exactly what RustyN64
//! writes into RDRAM), the comparison is a direct byte compare of the framebuffer
//! region.
#![allow(
    clippy::doc_markdown,
    reason = "narrative test docs name RustyN64/RDRAM/Angrylion in prose"
)]
#![allow(
    clippy::cast_possible_truncation,
    reason = "vector geometry and command lengths are small, well within u32"
)]

use rustyn64_test_harness::conformance::{first_mismatch, parse, replay, vector_bytes};

/// Assert RustyN64 reproduces the Angrylion golden framebuffer for `name`.
///
/// The vector's bytes come from `conformance::RDP_VECTORS`, the single source of
/// truth shared with the accuracy battery — so a vector can never be exercised
/// here while being invisible to the battery (or vice versa), and a name typo
/// fails loudly instead of silently skipping.
fn assert_matches(name: &str) {
    assert_matches_bytes(name, vector_bytes(name));
}

/// As [`assert_matches`], for a vector loaded at run time (the fuzz corpus, which
/// is read from disk rather than compiled into the binary). Reports the first
/// differing pixel on failure.
fn assert_matches_bytes(name: &str, bytes: &[u8]) {
    let Some(m) = first_mismatch(bytes) else {
        return;
    };
    assert!(
        !m.got.is_empty(),
        "{name}: framebuffer length differs from the golden"
    );
    panic!(
        "{name}: framebuffer differs from the Angrylion golden at pixel \
         ({},{}): got {:02X?}, golden {:02X?}",
        m.x, m.y, m.got, m.golden,
    );
}

#[test]
fn fill_rect_16_matches_angrylion() {
    assert_matches("fill_rect_16");
}

/// **A `Fill Rectangle` in 1-CYCLE mode goes through the COMBINER (R-21).**
///
/// In FILL mode the rectangle writes the `SET_FILL_COLOR` register; in 1-/2-cycle
/// mode the hardware rasterizes it like any other primitive. This vector
/// distinguishes them: the combine emits the prim color `0x224466` while the fill
/// register holds a clearly different green. Angrylion renders the prim color
/// (`0x2219`), so a renderer that ignores the cycle type and writes the fill
/// register produces green and fails.
#[test]
fn fill_rect_1cycle_16_matches_angrylion() {
    assert_matches("fill_rect_1cycle_16");
}

/// **A `Fill Rectangle` in 2-CYCLE mode goes through BOTH combiner cycles (R-21).**
///
/// The 1-cycle vector above leaves the 2-cycle branch unpinned, and 2-cycle takes a
/// distinct path: `combine()` evaluates cycle 0 first and feeds its output to cycle
/// 1 as the `COMBINED` input. Here cycle 0 emits the env color `0x88AACC` and cycle
/// 1 selects `COMBINED`, so the three candidate outcomes are all distinguishable —
/// env `0x8D73` means the chain ran, black means cycle 0 was skipped, and the green
/// fill register `0x07C1` means the cycle type was ignored. Angrylion renders
/// `0x8D73`.
#[test]
fn fill_rect_2cycle_16_matches_angrylion() {
    assert_matches("fill_rect_2cycle_16");
}

/// **A CI4 texture resolves through the TLUT (R-18).**
///
/// The first committed vector to exercise `Load Tlut` at all — the color-indexed
/// path had **zero** oracle coverage, and it is the path every Ocarina of Time
/// triangle renders through (`fmt=2 size=0`, combiner a pure `TEXEL0`
/// pass-through), so a CI4 fetch resolving to 0 is what would produce R-18's
/// black frame.
///
/// Eight indices `0..7` map to eight distinct, **non-zero** palette entries —
/// including index 0 — so neither an unloaded TLUT (reads all-zero, renders
/// black) nor a black index-0 entry can be mistaken for a correct fetch.
///
/// The encoding follows N64brew *…/Commands* §0x30 exactly. A first attempt did
/// not, and Angrylion faithfully rendered the resulting near-empty palette; that
/// golden was **discarded rather than committed**, because pinning it would have
/// made an authoring error the spec.
#[test]
fn tex_tri_ci4_tlut_16_matches_angrylion() {
    assert_matches("tex_tri_ci4_tlut_16");
}

/// **`Load Block`'s texel count is INCLUSIVE of `lower_right.s` (R-18).**
///
/// The first committed vector to exercise `Load Block` (0x33) at all — every other
/// texture vector loads through `Load Tile`. That was a real gap: Ocarina of Time
/// issues **4,374** `Load Block`s of its 74,508 commands.
///
/// §0x33's prose reads *"`lower_right.s - upper_left.s` determines the number of
/// texels"* — no `+1` — while `Load Tile` is inclusive, so the two readings
/// disagree and prose cannot settle it. This vector does: with `uls = 0,
/// lrs = 1` it loads either **one** texel or **two**, and Angrylion loads two.
/// `load_block`'s `shi - slo + 1` is therefore right.
///
/// Deliberately minimal — a single line, two texels, `dxt = 0` — so that neither
/// the odd-line swap nor any multi-line TMEM layout can confound the answer. Two
/// earlier, larger `Load Block` vectors were discarded for exactly that reason.
#[test]
fn load_block_count_16_matches_angrylion() {
    assert_matches("load_block_count_16");
}

/// **A CI tile with `tlut_en` CLEAR gets no palette lookup (R-18).**
///
/// Byte-identical to `tex_tri_ci4_tlut_16` except for `Set Other Modes` bit 47,
/// so any difference is attributable to that one bit. N64brew *…/Commands* §0x2F
/// makes `tlut_en` — not the tile's format field — the flag that enables the
/// lookup, and the oracle agrees emphatically: with the flag set the eight
/// columns render the full palette; with it clear they render **all black**.
///
/// This matters because keying the lookup off the format alone is wrong in *both*
/// directions — it palette-maps a CI tile that asked not to be, and fails to
/// palette-map a non-CI tile that asked to be.
#[test]
fn ci4_tlut_disabled_16_matches_angrylion() {
    assert_matches("ci4_tlut_disabled_16");
}

/// **A flat Fill Triangle matches Angrylion (regression guard for R-14).**
///
/// This left-major triangle (a vertical left edge at x=2, the hypotenuse widening
/// `DxMDy = 0.25` per **pixel** row) renders as a near-vertical line — over its 4
/// rows the right edge only reaches x≈2.75, so only column 2 is covered. It once
/// caught the 4× edge-slope bug: `triangle_fill` was multiplying the per-pixel
/// slope by the sub-scanline offset in quarter-pixel units (`y = line*4 + sub`)
/// without the compensating `>> 2`, drawing a staircase. Fixed (the slopes are
/// pre-shifted `>> 2` at decode); this vector now guards against a regression.
#[test]
fn fill_tri_16_matches_angrylion() {
    assert_matches("fill_tri_16");
}

/// A wider flat triangle (`DxMDy = 1.0` px/row) — a real multi-column staircase,
/// exercising the edge-walk across columns.
#[test]
fn fill_tri_wide_16_matches_angrylion() {
    assert_matches("fill_tri_wide_16");
}

/// A right-major triangle with a **negative** minor-edge slope (`DxMDy = -1.0`),
/// so the edge leans left — exercises sign-extension and the arithmetic `>> 2`
/// (rounds toward −∞) on the R-14 fix.
#[test]
fn fill_tri_neg_16_matches_angrylion() {
    assert_matches("fill_tri_neg_16");
}

/// A **FILL-mode** triangle with fractional edges (left 2.5, right 6.5). FILL mode
/// renders without sub-pixel accuracy (the wiki: "upper-left rounded down,
/// lower-right rounded up"), so the fractional edges round to whole pixels and
/// columns 2–6 fill — which RustyN64's whole-pixel span already matches. (The
/// *sub-pixel* coverage that would exclude a partially-covered column applies only
/// in 1-/2-cycle mode; see the coverage rewrite.)
#[test]
fn fill_tri_frac_16_matches_angrylion() {
    assert_matches("fill_tri_frac_16");
}

/// A **1-cycle-mode** shaded triangle with a fractional left edge (2.5) and right
/// edge (6.5). Here sub-pixel coverage applies: column 2 is excluded (its top-left
/// sample at 2.0 is outside the span, AA off), columns 3–5 are fully covered, and
/// column 6 is *partially* covered — Angrylion stores the coverage in the pixel, so
/// column 6 is `0xf800` (coverage MSB 0) while 3–5 are `0xf801`. Guards the 2c
/// sub-pixel coverage path (inclusion + coverage write-back).
#[test]
fn shade_tri_frac_16_matches_angrylion() {
    assert_matches("shade_tri_frac_16");
}

/// The same 1-cycle fractional triangle with a **z-suffix** (`z_update` on): the
/// depth path applies the identical sub-pixel coverage as the no-Z shaded path, so
/// column 2 is excluded and column 6 partial. Guards `depth_span`'s coverage wiring.
#[test]
fn shade_depth_tri_frac_16_matches_angrylion() {
    assert_matches("shade_depth_tri_frac_16");
}

/// A 1-cycle shaded triangle into a **32-bit RGBA8888** color image (dither off).
/// Exercises the 32-bit write path: a fully-covered interior pixel is the shade RGB
/// `0x112233` plus the coverage alpha `0xE0`.
#[test]
fn shade_tri_32_matches_angrylion() {
    assert_matches("shade_tri_32");
}

/// A 1-cycle shaded triangle into a **32-bit RGBA8888** color image with the RDP's
/// default **magic ordered dither ON** (`Set Other Modes` RGB dither mode 0). The
/// flat shade `0x112233` is dithered per pixel by the 4×4 magic matrix: a channel
/// rounds up to the next 5-bit level (`(c & 0xf8) + 8`) where the matrix cell is
/// below the channel's low 3 bits, so interior pixels vary (e.g. `0x112238`,
/// `0x182838`) rather than staying flat. Guards the `apply_rgb_dither` path against
/// the Angrylion `rgb_dither` reference.
#[test]
fn dither_tri_32_matches_angrylion() {
    assert_matches("dither_tri_32");
}

/// A 1-cycle **Gouraud-gradient** shaded triangle into a 32-bit image (dither off).
/// The first vector to exercise shade *interpolation* rather than a flat color: R
/// carries a per-x gradient (`dx.R = -0x10`/pixel from base `0xF0`) and G a
/// per-major-edge gradient (`de.G = +0x08`/scanline from base `0x40`); B is flat.
/// Validates `interpolate_shade` (base + dx + de, i16 snap) against Angrylion.
#[test]
fn shade_grad_tri_32_matches_angrylion() {
    assert_matches("shade_grad_tri_32");
}

/// A 1-cycle **textured** triangle (16-bit RGBA5551) — the first vector to validate
/// `interpolate_st` / `fetch_texel` against Angrylion, via the v2 `.rvec` preload (an
/// 8-texel ramp placed in RDRAM, loaded by `Load Tile`, sampled with a texel0
/// combiner passthrough). It has an S gradient of `1.0` per pixel, but because the
/// RDP texel coordinate is **s.5** the texel index is `SSS >> 5`, so `SSS = 0..5`
/// across the columns all resolve to texel 0 (red) — the golden is a solid-red
/// triangle. **R-13 (RESOLVED).** This vector was `#[ignore]`d for a long time behind
/// a thrice-wrong diagnosis; the real story was two things: (1) the vector used
/// `Set Other Modes` with `bi_lerp0 = 0`, which selects the RDP's YUV color-convert
/// path — with the convert coefficients unset that zeroes an RGBA texel, so Angrylion
/// rendered an all-black triangle (not a RustyN64 gap — a vector bug); fixed by
/// setting `bi_lerp0 = 1`. (2) RustyN64's `interpolate_st` used `v >> 16` directly as
/// the texel index (no `>> 5`), 32× too fast — fixed. Both land together and this now
/// passes.
#[test]
fn tex_tri_16_matches_angrylion() {
    assert_matches("tex_tri_16");
}

/// **Primitive base-tile threading (R-13).** The 8-color ramp is loaded into tile 3
/// (at a non-zero TMEM word) and the triangle names tile 3 in its command (bits 50:48).
/// The golden is byte-identical to `tex_tri_16` (same ramp, same triangle, just via a
/// non-zero tile), which is exactly the point: a renderer that hardwires tile 0 samples
/// the unloaded low TMEM and renders black. Guards `combined_color`'s tile selection.
#[test]
fn tex_tri_base_tile_16_matches_angrylion() {
    assert_matches("tex_tri_base_tile_16");
}

/// A textured triangle with a **constant** texture coordinate (`dsdx = 0`, `S = 0`),
/// so every covered pixel samples texel 0 = red — independent of the R-13 `>> 5`
/// coordinate scale. It isolates the texture *sampler* (Load Tile → TMEM →
/// `fetch_texel` → texel0 combiner) end to end from the coordinate advance, and it is
/// the minimal proof that the `bi_lerp0 = 1` fix makes the RGBA texel path render.
#[test]
fn tex_tri_fixed_16_matches_angrylion() {
    assert_matches("tex_tri_fixed_16");
}

/// A **4-bit (I4) textured triangle** — the hardware-canonical 4-bit texture path.
/// There is no 4-bit texel *load* on the N64 (a 4-bit texture-image load is invalid;
/// Angrylion crashes the pipeline, ledger R-7): games load 4-bit textures by setting
/// an 8-bit texture image + 8-bit LOAD tile, loading half as many texels raw, then
/// rendering with a SEPARATE 4-bit tile that extracts nibbles at fetch. This vector
/// drives that path — eight I4 texels packed two-per-byte, an 8-bit `Load Tile`, then
/// a 4-bit render tile — and proves RustyN64's existing 8-bit load + 4-bit `fetch_texel`
/// reproduce Angrylion byte-for-byte (no new "4-bit load" code, matching hardware).
#[test]
fn tex_tri_i4_16_matches_angrylion() {
    assert_matches("tex_tri_i4_16");
}

/// **Tile-coordinate CLAMP for a point-sampled textured triangle (R-13).** A 4-texel
/// 16-bit tile (`SH = 3`, `clamp_s = 1`) is sampled across a triangle whose S advances
/// one texel/pixel, so two columns run past the tile — they must clamp to the last
/// texel (white), giving `R,G,B,W,W,W`. Exercises the `sample_coord` transform
/// (shift → tile-origin subtraction → clamp → mask): the over-`SH` clamp to
/// `(SH>>2)-(SL>>2)`. RustyN64's pre-R-13 sampler ignored the tile size and would
/// read unrelated texels here.
#[test]
fn tex_tri_clamp_16_matches_angrylion() {
    assert_matches("tex_tri_clamp_16");
}

/// **Tile-coordinate WRAP for a point-sampled textured triangle (R-13).** As
/// `tex_tri_clamp_16` but the tile uses `mask_s = 2` (no clamp), so the coordinate
/// wraps mod 4 — the two over-tile columns read texels 0,1 again, giving
/// `R,G,B,W,R,G`. Together with the clamp vector this pins both branches of the
/// `sample_coord` transform against Angrylion.
#[test]
fn tex_tri_wrap_16_matches_angrylion() {
    assert_matches("tex_tri_wrap_16");
}

/// **The N64 3-point BILINEAR filter (`sample_type = 1`, R-13).** An 8×8 gradient
/// texture sampled with S and T advancing 0.5 texel/pixel, so each covered pixel is
/// a 3-point blend of its four neighbors — R interpolates `0,2,4,6,8,10` (the
/// half-texel averages), where point sampling would hard-step `0,0,4,4,8,8`. Both
/// fractions vary across the triangle, so pixels exercise the lower-left AND
/// upper-right (`sfrac+tfrac >= 0x20`) branches of `bilinear_3point`.
#[test]
fn tex_tri_bilinear_16_matches_angrylion() {
    assert_matches("tex_tri_bilinear_16");
}

/// **The mid-texel filter (Set Other Modes bit 44, R-13).** The same bilinear setup as
/// `tex_tri_bilinear_16` but over a non-planar checkerboard with `mid_texel` set: at the
/// exact texel center (`sfrac == tfrac == 0x10`) the RDP averages the four neighbors
/// instead of the 3-point triangle pick. Non-vacuous because the checkerboard makes the
/// two disagree — the golden carries the midpoint value (`0x8001`, R=16) that a 3-point
/// pick (checkerboard extremes) never produces; a renderer ignoring bit 44 mismatches it.
#[test]
fn tex_tri_mid_texel_16_matches_angrylion() {
    assert_matches("tex_tri_mid_texel_16");
}

/// **The derivative-computed LOD fraction (R-13).** A 2-cycle textured triangle whose
/// texture coordinate advances `dx.S = 48` per pixel but `dy.S = 112` per scanline
/// (with `de = 0`), so the LOD is the larger of the two taps and settles at **112** —
/// which is what pins the `dy` tap: an implementation reading `de` for it would get 48.
/// With `level = 2` in the triangle command the LOD is not "distant", so the fraction is
/// the real interpolation weight `((112 << 3) >> 1) & 0xff = 0xc0` rather than the
/// saturated `0xff`. Cycle 1 emits `(One - Zero) * LODFrac + Zero`, so the pixel **is**
/// the fraction — the golden `0xc631` (RGB 24,24,24 = 0xc0) versus black if the input
/// reads zero.
#[test]
fn tex_tri_lodfrac_16_matches_angrylion() {
    assert_matches("tex_tri_lodfrac_16");
}

/// **LOD-driven mip tile selection (`tex_lod_en`, R-13).** Same LOD setup as
/// `tex_tri_lodfrac_16` (LOD 112, `level = 2`, so `l_tile = 1`), with three 1-texel
/// tiles holding distinct colors, so the pixel names which tile the LOD selected.
#[test]
fn tex_tri_mip_tile_16_matches_angrylion() {
    assert_matches("tex_tri_mip_tile_16");
}

/// **The bilinear MASK-WRAP SEAM (`sdiff`/`tdiff`, R-13).** A 2-texel tile
/// (`mask_s = 1`, red/green) sampled bilinearly across the wrap: at `S = 1.5` the
/// base is the top texel, so the neighbor must WRAP to texel 0 (red) — the seam
/// column blends green+red, not green+black (the pre-fix `base+1` read of an
/// unloaded texel). Non-vacuous because the wrapped texel differs from the unloaded
/// one; pins `mask_coupled`'s `sdiff = -1` seam handling against Angrylion.
#[test]
fn tex_tri_bilinear_wrap_16_matches_angrylion() {
    assert_matches("tex_tri_bilinear_wrap_16");
}

/// **2-cycle mode with a second texel from `tile+1` (R-13).** Two 1-texel tiles
/// (tile 0 = red, tile 1 = green); a 2-cycle combine outputs TEXEL0 in both cycles.
/// The hardware swaps texel0/texel1 before cycle 1, so cycle 1's TEXEL0 reads tile 1
/// — the pixel is GREEN. Non-vacuous: a missing texel1 sample or no swap would leave
/// cycle 1 reading tile 0 (red). Pins the two-tile sample + the `combine` texel swap.
#[test]
fn tex_tri_2cycle_16_matches_angrylion() {
    assert_matches("tex_tri_2cycle_16");
}

/// **The `PRIM_LOD_FRAC` combiner input (R-10).** `Set Prim Color` carries
/// `prim_lod_frac = 0x80`; the combine computes `(One - Zero) * PrimLODFrac` (rgb mul
/// select 14), so the triangle is a mid-gray `0x80` (Angrylion emits `0x8421`). Without
/// the input wired it reads 0 and the triangle is black — non-vacuous. Pins that
/// `Set Prim Color` extracts `prim_lod_frac` and the combiner routes mul-select 14 to it.
#[test]
fn tex_tri_primlodfrac_16_matches_angrylion() {
    assert_matches("tex_tri_primlodfrac_16");
}

/// **The `Set Convert` K4 (rgb sub-B select 7) and K5 (rgb mul select 15) inputs (R-10).**
/// `Set Convert` carries `K4 = 0x040`, `K5 = 0x0C0`; the combine computes `(One - K4) * K5`
/// (Angrylion emits `0x94a5`). Without either input wired both read 0 and the result is
/// `(One - 0) * 0 = 0` (black) — non-vacuous. Pins the `Set Convert` (0x2C) K4/K5 extract
/// and the two combiner selects.
#[test]
fn tex_tri_convert_k45_16_matches_angrylion() {
    assert_matches("tex_tri_convert_k45_16");
}

/// **A NEGATIVE `Set Convert` K4 (bit 8 set) — the sign-extension proof (R-10).**
/// `K4 = 0x1C0` is raw 9-bit `448` but `-64` after the RDP's `special_9bit` expand
/// (Angrylion `combiner.c:481`); with `K5 = 0x040` the combine `(One - K4) * K5`
/// is `(256 - (-64)) * 64 >> 8 = 80` (gray `0x5295`). Read raw-positive it would be
/// `(256 - 448) * 64 < 0` → clamped black, so this pins that `combine_channel`'s
/// `special_expand` sign-extends K4 exactly like Angrylion's exttable — the path the
/// bit-8-clear `tex_tri_convert_k45_16` vector cannot reach.
#[test]
fn tex_tri_convert_kneg_16_matches_angrylion() {
    assert_matches("tex_tri_convert_kneg_16");
}

/// **The chroma-key KeyCenter (rgb sub-B select 6) and KeyScale (rgb mul select 6)
/// inputs (R-10).** `Set Key GB`/`Set Key R` program per-channel center
/// `[0x20, 0x40, 0x60]` and scale `[0x40, 0x80, 0xC0]`; the combine `(One − center) *
/// scale >> 8` is `[56, 96, 120]` → RGBA5551 `0x3b1f` (Angrylion's golden). Without
/// either input wired both read 0 and the result is `(One − 0) * 0 = 0` (black) —
/// non-vacuous. Pins the `Set Key` (0x2A/0x2B) center/scale decode **and** the two
/// combiner selects end-to-end against Angrylion.
#[test]
fn tex_tri_chromakey_16_matches_angrylion() {
    assert_matches("tex_tri_chromakey_16");
}

/// **The chroma-key alpha compare (`key_en`, Set Other Modes bit 40) — R-10.** With
/// `key_en`, the combiner outputs the sub-A "chromabypass" color (Shade) and derives
/// the pixel alpha from `chroma_key_min` over the pre-`>>8` 17-bit combined color + the
/// `Set Key` widths. The **key alpha is made observable** by enabling alpha-compare
/// (bit 0) with a `Set Blend Color` threshold of `0x80`: the Shade triangle is written
/// only where the key alpha `>= 0x80`. The combine (`rgb_a=rgb_b=Shade` → 17-bit `0x80`,
/// `width_r=0x10`) yields key alpha `0x80` exactly, so the triangle IS drawn — and a
/// broken `chroma_key_min` shifting it below `0x80` makes the triangle vanish (a −1
/// mutation is verified to fail), while clearing `key_en` outputs the combined color
/// (black) instead of Shade. Pins the `key_en`/`key_width` decode, the 17-bit combined
/// value, and `chroma_key_min` end-to-end against Angrylion (the `chroma_key_min` fold
/// itself is additionally unit-tested with hand-computed values).
#[test]
fn tex_tri_chromakey_alpha_16_matches_angrylion() {
    assert_matches("tex_tri_chromakey_alpha_16");
}

/// A **COPY-mode Texture Rectangle** (16-bit) — the first texture path validated
/// against Angrylion. Copy mode blits texels straight from TMEM to the color image
/// (no combiner, no 1-cycle texel pipeline), so it sidesteps the gaps `tex_tri_16`
/// pins. A 4×2 texture (8 byte-asymmetric texels) is preloaded (v2 `.rvec`), loaded
/// by `Load Tile`, and blitted 1:1 (`DsDx = 4.0`, `DtDy = 1.0`) into a 4×2 color
/// image, so the framebuffer equals the source texels verbatim. Exercises Set Texture
/// Image / Set Tile / Set Tile Size / Load Tile / `texture_rectangle` end-to-end
/// against the oracle (RustyN64 previously only round-trip-tested this internally).
#[test]
fn tex_rect_copy_16_matches_angrylion() {
    assert_matches("tex_rect_copy_16");
}

/// A COPY-mode Texture Rectangle blitted to an **offset position** — the same 4×2
/// texture, 1:1-blitted into the (2,2)..(5,3) sub-rectangle of an 8×8 color image,
/// the rest staying background 0. Exercises the destination positioning (`XH`/`YH`)
/// and the surrounding-pixel/scissor behavior the origin blit did not.
#[test]
fn tex_rect_offset_16_matches_angrylion() {
    assert_matches("tex_rect_offset_16");
}

/// A COPY-mode Texture Rectangle of a full **8×8** texture (64 texels) 1:1-blitted
/// into an 8×8 color image — exercises the copy load + blit at a larger scale than
/// the small vectors: the full tile stride (`line = 2`), all eight rows, and the
/// odd-row TMEM swap across a bigger surface. The texture is an RGBA5551 gradient.
#[test]
fn tex_rect_8x8_16_matches_angrylion() {
    assert_matches("tex_rect_8x8_16");
}

/// **Alpha-compare** gates the pixel write. A 1-cycle flat-red shaded triangle whose
/// combiner alpha (the interpolated shade alpha) ramps across X (`dx.A = 0x30`), with
/// alpha-compare enabled and a `Set Blend Color` alpha threshold of `0x80`. Columns
/// whose alpha is below the threshold are killed (stay background 0); only the higher-
/// alpha columns draw red. Guards the `alpha_compare_en` write gate.
#[test]
fn alpha_compare_16_matches_angrylion() {
    assert_matches("alpha_compare_16");
}

/// **Alpha-compare on the depth path.** The same shade-alpha ramp + `0x80` threshold
/// as `alpha_compare_16`, but on a z-suffixed triangle (op 0x0D) with `z_update` on
/// and `z_compare` off — so every pixel passes the depth test and alpha-compare is
/// the sole gate. The color equals the no-Z case (low-alpha columns killed), which
/// guards that `depth_span` applies alpha-compare and skips the killed pixels' write.
#[test]
fn alpha_compare_z_16_matches_angrylion() {
    assert_matches("alpha_compare_z_16");
}

/// **`cvg_dest = full`** coverage write-back. The same fractional-edge shaded
/// triangle as `shade_tri_frac_16`, but with `Set Other Modes` `cvg_dest = 2`
/// (full): the partially-covered right-edge column stores **full** coverage (7 →
/// RGBA5551 alpha bit set, `0xf801`) instead of the clamp `(count-1) & 7`
/// (`0xf800`). Guards the `cvg_dest = full` write-back path.
#[test]
fn cvg_dest_full_16_matches_angrylion() {
    assert_matches("cvg_dest_full_16");
}

/// A 1-cycle 32-bit shaded triangle whose combiner outputs the **primitive** color
/// (the cyc1 `rgb_d`/`a_d` add-inputs both select `prim` = 3; 1-cycle mode evaluates
/// the cyc1 selects), not the shade. The shade block is a distinct
/// color (`0x112233`), so a combiner that wrongly emitted the shade would show it
/// instead of the prim `0x224466` — this **discriminates** the primitive combiner
/// input (`Set Prim Color`) from the shade path. Validates the combiner prim mux.
#[test]
fn prim_combiner_32_matches_angrylion() {
    assert_matches("prim_combiner_32");
}

/// A **magnified** COPY-mode Texture Rectangle (`DsDx = 2.0`, 0.5 texel/pixel). The
/// RDP copies **4 pixels per cycle**: within a cycle it reads 4 consecutive texels
/// (`base..base+3` from a 64-bit TMEM word) and the base advances by `DsDx × 4`
/// texels per cycle, so an 8-texel ramp magnified 2× reads texels `0,1,2,3,2,3,4,5`
/// (not the naive per-pixel `0,0,1,1,2,2,3,3`). Guards the 4-pixels-per-cycle copy.
#[test]
fn tex_rect_mag_16_matches_angrylion() {
    assert_matches("tex_rect_mag_16");
}

/// Per-family lower bounds on the committed seeded-fuzz corpus, keyed by filename
/// prefix. The gate fails if any family has fewer than its floor, so a checkout or
/// packaging error that drops a corpus directory — or a later edit that removes one
/// family's vectors while others grow — cannot make the oracle gate pass without
/// replaying that family's coverage (the accuracy oracle must never pass vacuously).
/// Add a row when a family is committed; never let a floor exceed its committed count.
const FUZZ_FAMILY_FLOORS: &[(&str, usize)] = &[("fz_fill_", 48), ("fz_scis_", 48), ("fz_tri_", 48)];

/// The **seeded-fuzz corpus gate.** Every committed `.rvec` under `tests/vectors/fuzz/`
/// is a curated candidate from the reproducible generator (`vectors-gen/driver.c`
/// `--fuzz <dir> <seed> <count> [family]`): only candidates that already matched the
/// Angrylion golden were committed, so this replays each and asserts the byte-exact
/// match still holds. It scales to any corpus size without a `#[test]` per vector.
/// The corpus is committed, so a missing directory or a below-floor **per-family**
/// count is a failure, not a pass ([[vacuous-pass-in-rom-tests]]).
#[test]
fn fuzz_corpus_matches_angrylion() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/fuzz");
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("committed fuzz corpus directory {dir} is unreadable: {e}"));
    let mut names: Vec<std::path::PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "rvec"))
        .collect();
    names.sort(); // deterministic order
    for path in &names {
        let bytes = std::fs::read(path).expect("read fuzz vector");
        let name = path.file_stem().unwrap().to_string_lossy();
        assert_matches_bytes(&name, &bytes);
    }
    // Each committed family must still be present at (or above) its floor.
    let stems: Vec<String> = names
        .iter()
        .map(|p| p.file_stem().unwrap().to_string_lossy().into_owned())
        .collect();
    for &(prefix, floor) in FUZZ_FAMILY_FLOORS {
        let count = stems.iter().filter(|s| s.starts_with(prefix)).count();
        assert!(
            count >= floor,
            "fuzz family '{prefix}' has {count} vector(s), below its floor of {floor} — a \
             checkout/packaging error may have dropped vectors",
        );
    }
    eprintln!(
        "fuzz corpus: {} vector(s) match the Angrylion golden",
        names.len()
    );
}

/// **Curation dev-tool** (not a gate): replay every `.rvec` in `$RUSTYN64_FUZZ_DIR`
/// and print a PASS/FAIL partition without asserting. Used to sift a freshly
/// generated candidate batch — only the PASS set is copied into `tests/vectors/fuzz/`
/// and committed, so an unmodeled RDP corner is dropped rather than baked in. Run:
/// `RUSTYN64_FUZZ_DIR=/path cargo test -p rustyn64-test-harness --test rdp_conformance
/// -- --ignored --nocapture curate_fuzz_candidates`.
#[test]
#[ignore = "dev tool: sifts an external candidate batch, needs $RUSTYN64_FUZZ_DIR"]
fn curate_fuzz_candidates() {
    let dir = std::env::var("RUSTYN64_FUZZ_DIR").expect("set RUSTYN64_FUZZ_DIR");
    let mut names: Vec<std::path::PathBuf> = std::fs::read_dir(&dir)
        .expect("read candidate dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "rvec"))
        .collect();
    names.sort();
    let (mut pass, mut fail) = (Vec::new(), Vec::new());
    for path in &names {
        let bytes = std::fs::read(path).expect("read candidate");
        let v = parse(&bytes);
        let name = path.file_stem().unwrap().to_string_lossy().into_owned();
        let got = replay(&v);
        if got == v.golden_fb {
            pass.push(name);
        } else {
            let bpp = v.bpp as usize;
            let mut detail = String::from("len mismatch");
            for i in (0..got.len().min(v.golden_fb.len())).step_by(bpp) {
                if got[i..i + bpp] != v.golden_fb[i..i + bpp] {
                    let px = i / bpp;
                    detail = format!(
                        "{}x{} px({},{}) got {:02X?} golden {:02X?}",
                        v.width,
                        v.height,
                        px as u32 % v.width,
                        px as u32 / v.width,
                        &got[i..i + bpp],
                        &v.golden_fb[i..i + bpp],
                    );
                    break;
                }
            }
            fail.push(format!("{name}: {detail}"));
        }
    }
    eprintln!(
        "curate: {} pass, {} fail (of {})",
        pass.len(),
        fail.len(),
        names.len()
    );
    for f in &fail {
        eprintln!("  FAIL {f}");
    }
    for p in &pass {
        println!("PASS {p}");
    }
}

/// **Coverage must match Angrylion in the hidden plane, not just on screen**
/// (ledger R-24).
///
/// Every other vector in this file compares rendered pixels, and that is exactly
/// why the defect this pins survived all 164 of them: the N64 keeps anti-aliasing
/// coverage for a 16-bit color image in RDRAM's hidden 9th-bit plane, which is
/// invisible in the framebuffer. The RDP computed coverage correctly and stored
/// only its top bit — so the VI read back 0 or 4 and never 7, and every
/// coverage-gated VI filter silently degenerated.
///
/// `aa_tri_coverage_16` is the first vector rendered with `aa_enable` in 1-cycle
/// mode rather than FILL, so the rasterizer actually produces sub-pixel coverage,
/// and the first emitted at `.rvec` **v3**, which carries the oracle's plane.
///
/// **`#[ignore]`d, and the reason is two findings this vector surfaced on its
/// first run — not a flaky test.** It is committed in this state deliberately:
/// the infrastructure (`.rvec` v3, the generator's plane dump, the parser,
/// `replay_with_hidden`) is what took the work, and the two gaps below are each
/// worth their own change rather than being smuggled into this one.
///
/// 1. ~~We render nothing for this vector.~~ **FIXED.** It was ledger R-21's
///    still-open half: a *flat* triangle took the fill register whatever the
///    cycle type, because `has_color` keyed off the presence of a shade/texture
///    block rather than the cycle type. The framebuffer now matches the oracle.
///
///    The first version of this vector could not have shown that, and the reason
///    is worth keeping: its combine emitted black, so "drawn black" and "not
///    drawn at all" were the same framebuffer and the comparison was **vacuous**.
///    It now selects the prim color (adder input 3) and renders white.
///
/// 1b. **What remains: we write coverage for 28 of 64 pixels, the oracle for 64.**
///    Every divergence is `got 0, want 3` on a pixel we demonstrably *drew* (the
///    framebuffer matches), so the write-back is not reaching the interior. That
///    is a third defect, distinct from R-24's missing store and from R-21's path
///    selection, and it needs its own investigation rather than a widened test.
/// 2. **The hidden plane's power-on state differs.** Angrylion clears it to `3`
///    (`HB_CLEAN` in its `rdram.c`), we power on at `0`. So untouched pixels can
///    never match, whatever the renderer does, and a comparison of raw planes is
///    not yet meaningful. Whether `3` is the hardware's reset state or an
///    Angrylion convention is not established here and must not be assumed —
///    ADR 0004 makes power-on state a documented value, not a copied one.
///
/// Un-ignore this once (1) is fixed and (2) is decided. Until then it would fail
/// for reasons that are not the thing it is named after, which is worse than not
/// running: a red test nobody can act on gets ignored by hand instead.
///
/// Mutation check once live: remove either `write_coverage` call (the no-Z span
/// or `depth_span`) and it must go red. Both were needed — fixing only the first
/// left 74.91% of a real frame's pixels at exactly `cvg4`.
#[test]
#[ignore = "blocked on findings 1b and 2 recorded above: coverage reaches only \
            28 of 64 drawn pixels, and the plane's power-on state differs"]
fn aa_triangle_coverage_matches_angrylion_in_the_hidden_plane() {
    let bytes = include_bytes!("vectors/aa_tri_coverage_16.rvec");
    let v = parse(bytes);
    let golden_hidden = v
        .golden_hidden
        .expect("aa_tri_coverage_16 must be a v3 vector carrying the hidden plane");
    let (fb, hidden) = rustyn64_test_harness::conformance::replay_with_hidden(&v);

    // The framebuffer still has to match, or a "coverage" agreement could be
    // reached by rendering something else entirely.
    assert_eq!(fb, v.golden_fb, "framebuffer diverged from the oracle");

    // The plane is the point. Compare per pixel so a failure names the pixel
    // rather than reporting that two 64-byte blobs differ.
    assert_eq!(hidden.len(), golden_hidden.len(), "hidden plane length");
    let mut wrong = Vec::new();
    for (i, (got, want)) in hidden.iter().zip(golden_hidden).enumerate() {
        if got != want {
            wrong.push((i % v.width as usize, i / v.width as usize, *got, *want));
        }
    }
    assert!(
        wrong.is_empty(),
        "hidden coverage plane diverged from Angrylion at {} of {} pixels; \
         first few (x, y, got, want): {:?}",
        wrong.len(),
        hidden.len(),
        &wrong[..wrong.len().min(6)]
    );

    // Witness that the vector exercises what it claims: a plane of all-zeros
    // would "match" a renderer that writes nothing if the oracle also wrote
    // nothing, and an all-identical plane would not distinguish edges from
    // interior. Angrylion's plane must carry more than one distinct value.
    let mut seen: Vec<u8> = golden_hidden.to_vec();
    seen.sort_unstable();
    seen.dedup();
    assert!(
        seen.len() > 1,
        "the oracle's hidden plane is uniform ({seen:?}) — this vector cannot \
         distinguish a renderer that stores coverage from one that does not"
    );
}
