//! T-33-005 — the ParaLLEl-RDP / Angrylion conformance gate.
//!
//! Each `.rvec` vector under `tests/vectors/` is a golden reference generated by
//! running the **Angrylion** software RDP (the non-commercial study oracle, run
//! externally — see `vectors-gen/README.md` for the licence-clean generator) over
//! a fixed RDP command list. The vector carries *only outputs*: the command stream
//! (freely committable) and the golden framebuffer Angrylion rendered — no
//! Angrylion source or binary is vendored, keeping the licence boundary clean.
//!
//! This test replays each command stream through RustyN64's own RDP and asserts a
//! byte-for-byte match against the golden framebuffer. Because the command bytes
//! are stored big-endian (RustyN64's RDRAM layout) and the golden pixels are
//! stored as row-major big-endian logical values (which is exactly what RustyN64
//! writes into RDRAM), the comparison is a direct byte compare of the framebuffer
//! region.
#![allow(
    clippy::doc_markdown,
    reason = "narrative test docs name RustyN64/RDRAM/Angrylion in prose"
)]
#![allow(
    clippy::cast_possible_truncation,
    reason = "vector geometry and command lengths are small, well within u32"
)]

use rustyn64_core::Bus;

/// A parsed `.rvec` conformance vector.
struct Vector<'a> {
    fb_addr: u32,
    width: u32,
    height: u32,
    bpp: u32,
    cmd_addr: u32,
    /// Optional RDRAM preload (a texture a `Load Tile` reads), written before the
    /// command list runs. `(addr, bytes)`; empty when the vector carries none.
    preload_addr: u32,
    preload: &'a [u8],
    cmds: &'a [u8],
    golden_fb: &'a [u8],
}

/// Parse the `.rvec` container. The big-endian header is `"RVEC"`, a version, then
/// `fb_addr`, `width`, `height`, `bpp`, `cmd_addr`, `cmd_len`, `fb_len` — **v1** (9
/// words) stops there; **v2** (11 words) adds `preload_addr`, `preload_len`. The
/// body is the preload bytes (v2 only), then the command bytes, then the golden
/// framebuffer bytes.
fn parse(bytes: &[u8]) -> Vector<'_> {
    assert!(
        bytes.len() >= 36,
        "truncated .rvec: shorter than the header"
    );
    let u32_at =
        |i: usize| u32::from_be_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
    assert_eq!(u32_at(0), 0x5256_4543, "bad magic (expected RVEC)");
    let version = u32_at(4);
    assert!(
        version == 1 || version == 2,
        "unexpected vector version {version}"
    );
    let fb_addr = u32_at(8);
    let width = u32_at(12);
    let height = u32_at(16);
    let bpp = u32_at(20);
    let cmd_addr = u32_at(24);
    let cmd_len = u32_at(28) as usize;
    let fb_len = u32_at(32) as usize;
    // v2 carries a preload region (addr + len) in two extra header words.
    let (hdr, preload_addr, preload_len) = if version == 2 {
        assert!(bytes.len() >= 44, "truncated .rvec: v2 header incomplete");
        (44usize, u32_at(36), u32_at(40) as usize)
    } else {
        (36usize, 0u32, 0usize)
    };
    assert!(
        bpp == 2 || bpp == 4,
        "unsupported bpp {bpp} (expected 2 or 4)"
    );
    assert_eq!(
        cmd_len % 4,
        0,
        "command length is not a whole number of words"
    );
    // Checked so an implausible header can't silently wrap the pixel count.
    let expected_fb = (width as usize)
        .checked_mul(height as usize)
        .and_then(|n| n.checked_mul(bpp as usize))
        .expect("framebuffer dimensions overflow");
    assert_eq!(fb_len, expected_fb, "fb_len mismatch");
    let total = hdr
        .checked_add(preload_len)
        .and_then(|n| n.checked_add(cmd_len))
        .and_then(|n| n.checked_add(fb_len))
        .expect("payload sizes overflow");
    assert!(
        bytes.len() >= total,
        "truncated .rvec: header declares more payload than the file holds"
    );
    let preload = &bytes[hdr..hdr + preload_len];
    let cmd_start = hdr + preload_len;
    Vector {
        fb_addr,
        width,
        height,
        bpp,
        cmd_addr,
        preload_addr,
        preload,
        cmds: &bytes[cmd_start..cmd_start + cmd_len],
        golden_fb: &bytes[cmd_start + cmd_len..cmd_start + cmd_len + fb_len],
    }
}

/// Replay `v`'s command stream through RustyN64's RDP and return the rendered
/// framebuffer region (raw RDRAM bytes), which is directly comparable to the
/// golden bytes (both are row-major big-endian logical pixel values).
fn replay(v: &Vector<'_>) -> Vec<u8> {
    let mut bus = Bus::new();
    // Load the command list into RDRAM verbatim (big-endian words, as generated).
    let base = v.cmd_addr as usize;
    let fb = v.fb_addr as usize;
    let fb_len = (v.width * v.height * v.bpp) as usize;
    let pre = v.preload_addr as usize;
    assert!(
        base + v.cmds.len() <= bus.rdram.len()
            && fb + fb_len <= bus.rdram.len()
            && pre + v.preload.len() <= bus.rdram.len(),
        "vector addresses exceed RDRAM ({} bytes)",
        bus.rdram.len()
    );
    // Place the optional texture preload (big-endian, RustyN64's RDRAM layout) so a
    // Load Tile in the command list reads it, exactly as the generator placed it in
    // Angrylion's RDRAM before rendering the golden.
    bus.rdram[pre..pre + v.preload.len()].copy_from_slice(v.preload);
    bus.rdram[base..base + v.cmds.len()].copy_from_slice(v.cmds);

    // Point the DP FIFO at the list and drain it (one command per tick).
    bus.rdp.dpc_write(0, v.cmd_addr); // DPC_START
    bus.rdp.dpc_write(1, v.cmd_addr + v.cmds.len() as u32); // DPC_END
    let n_words = v.cmds.len() / 4;
    // A generous budget: multi-word triangle commands still retire in a handful
    // of ticks, so twice the word count cannot leave the FIFO mid-list.
    for _ in 0..(n_words * 2 + 16) {
        bus.rdp_tick();
    }

    bus.rdram[fb..fb + fb_len].to_vec()
}

/// Assert RustyN64 reproduces the Angrylion golden framebuffer for `name`,
/// reporting the first differing pixel on failure.
fn assert_matches(name: &str, bytes: &[u8]) {
    let v = parse(bytes);
    let got = replay(&v);
    if got == v.golden_fb {
        return;
    }
    // Locate the first mismatching pixel for a legible failure.
    let bpp = v.bpp as usize;
    for i in (0..got.len()).step_by(bpp) {
        if got[i..i + bpp] != v.golden_fb[i..i + bpp] {
            let px = i / bpp;
            let (x, y) = (px as u32 % v.width, px as u32 / v.width);
            panic!(
                "{name}: framebuffer differs from the Angrylion golden at pixel \
                 ({x},{y}): got {:02X?}, golden {:02X?}",
                &got[i..i + bpp],
                &v.golden_fb[i..i + bpp],
            );
        }
    }
    panic!("{name}: framebuffer length differs from the golden");
}

#[test]
fn fill_rect_16_matches_angrylion() {
    assert_matches("fill_rect_16", include_bytes!("vectors/fill_rect_16.rvec"));
}

/// **A flat Fill Triangle matches Angrylion (regression guard for R-14).**
///
/// This left-major triangle (a vertical left edge at x=2, the hypotenuse widening
/// `DxMDy = 0.25` per **pixel** row) renders as a near-vertical line — over its 4
/// rows the right edge only reaches x≈2.75, so only column 2 is covered. It once
/// caught the 4× edge-slope bug: `triangle_fill` was multiplying the per-pixel
/// slope by the sub-scanline offset in quarter-pixel units (`y = line*4 + sub`)
/// without the compensating `>> 2`, drawing a staircase. Fixed (the slopes are
/// pre-shifted `>> 2` at decode); this vector now guards against a regression.
#[test]
fn fill_tri_16_matches_angrylion() {
    assert_matches("fill_tri_16", include_bytes!("vectors/fill_tri_16.rvec"));
}

/// A wider flat triangle (`DxMDy = 1.0` px/row) — a real multi-column staircase,
/// exercising the edge-walk across columns.
#[test]
fn fill_tri_wide_16_matches_angrylion() {
    assert_matches(
        "fill_tri_wide_16",
        include_bytes!("vectors/fill_tri_wide_16.rvec"),
    );
}

/// A right-major triangle with a **negative** minor-edge slope (`DxMDy = -1.0`),
/// so the edge leans left — exercises sign-extension and the arithmetic `>> 2`
/// (rounds toward −∞) on the R-14 fix.
#[test]
fn fill_tri_neg_16_matches_angrylion() {
    assert_matches(
        "fill_tri_neg_16",
        include_bytes!("vectors/fill_tri_neg_16.rvec"),
    );
}

/// A **FILL-mode** triangle with fractional edges (left 2.5, right 6.5). FILL mode
/// renders without sub-pixel accuracy (the wiki: "upper-left rounded down,
/// lower-right rounded up"), so the fractional edges round to whole pixels and
/// columns 2–6 fill — which RustyN64's whole-pixel span already matches. (The
/// *sub-pixel* coverage that would exclude a partially-covered column applies only
/// in 1-/2-cycle mode; see the coverage rewrite.)
#[test]
fn fill_tri_frac_16_matches_angrylion() {
    assert_matches(
        "fill_tri_frac_16",
        include_bytes!("vectors/fill_tri_frac_16.rvec"),
    );
}

/// A **1-cycle-mode** shaded triangle with a fractional left edge (2.5) and right
/// edge (6.5). Here sub-pixel coverage applies: column 2 is excluded (its top-left
/// sample at 2.0 is outside the span, AA off), columns 3–5 are fully covered, and
/// column 6 is *partially* covered — Angrylion stores the coverage in the pixel, so
/// column 6 is `0xf800` (coverage MSB 0) while 3–5 are `0xf801`. Guards the 2c
/// sub-pixel coverage path (inclusion + coverage write-back).
#[test]
fn shade_tri_frac_16_matches_angrylion() {
    assert_matches(
        "shade_tri_frac_16",
        include_bytes!("vectors/shade_tri_frac_16.rvec"),
    );
}

/// The same 1-cycle fractional triangle with a **z-suffix** (`z_update` on): the
/// depth path applies the identical sub-pixel coverage as the no-Z shaded path, so
/// column 2 is excluded and column 6 partial. Guards `depth_span`'s coverage wiring.
#[test]
fn shade_depth_tri_frac_16_matches_angrylion() {
    assert_matches(
        "shade_depth_tri_frac_16",
        include_bytes!("vectors/shade_depth_tri_frac_16.rvec"),
    );
}

/// A 1-cycle shaded triangle into a **32-bit RGBA8888** colour image (dither off).
/// Exercises the 32-bit write path: a fully-covered interior pixel is the shade RGB
/// `0x112233` plus the coverage alpha `0xE0`.
#[test]
fn shade_tri_32_matches_angrylion() {
    assert_matches("shade_tri_32", include_bytes!("vectors/shade_tri_32.rvec"));
}

/// A 1-cycle shaded triangle into a **32-bit RGBA8888** colour image with the RDP's
/// default **magic ordered dither ON** (`Set Other Modes` RGB dither mode 0). The
/// flat shade `0x112233` is dithered per pixel by the 4×4 magic matrix: a channel
/// rounds up to the next 5-bit level (`(c & 0xf8) + 8`) where the matrix cell is
/// below the channel's low 3 bits, so interior pixels vary (e.g. `0x112238`,
/// `0x182838`) rather than staying flat. Guards the `apply_rgb_dither` path against
/// the Angrylion `rgb_dither` reference.
#[test]
fn dither_tri_32_matches_angrylion() {
    assert_matches(
        "dither_tri_32",
        include_bytes!("vectors/dither_tri_32.rvec"),
    );
}

/// A 1-cycle **Gouraud-gradient** shaded triangle into a 32-bit image (dither off).
/// The first vector to exercise shade *interpolation* rather than a flat colour: R
/// carries a per-x gradient (`dx.R = -0x10`/pixel from base `0xF0`) and G a
/// per-major-edge gradient (`de.G = +0x08`/scanline from base `0x40`); B is flat.
/// Validates `interpolate_shade` (base + dx + de, i16 snap) against Angrylion.
#[test]
fn shade_grad_tri_32_matches_angrylion() {
    assert_matches(
        "shade_grad_tri_32",
        include_bytes!("vectors/shade_grad_tri_32.rvec"),
    );
}

/// A 1-cycle **textured** triangle (16-bit RGBA5551) — intended as the first vector
/// to validate `interpolate_st` / `fetch_texel` against Angrylion, via the v2 `.rvec`
/// preload (an 8-texel ramp placed in RDRAM, loaded by `Load Tile`, sampled across
/// the triangle by a per-x S gradient with texel0 combiner passthrough).
///
/// **`#[ignore]`d — pins a REAL texture-path divergence RustyN64 does not yet model.**
/// The vector is **well-formed** (two earlier notes claiming a coordinate-scale bug,
/// then a malformed vector, are both retracted — the "malformed" one came from reading
/// an earlier *shade* vector's debug output). Correctly instrumented, Angrylion here
/// configures tile 0 (`size = 2`), advances the S coordinate (`SSS = 0..5` across the
/// columns), and fetches texel 0 = `(255,0,0,255)` = red **correctly** — yet the output
/// differs from RustyN64. The cause is two RDP behaviours RustyN64 does not model:
/// (1) the **1-cycle TEXEL0 pipeline** — Angrylion swaps `texel0_color = texel1_color`
/// before the combine, so a `TEXEL0` passthrough in 1-cycle mode is *pipelined*, not the
/// just-fetched texel; and (2) the **s10.5 texel-coordinate scale** — `SSS` spans < one
/// texel, so Angrylion point-samples texel 0 across the triangle while RustyN64's
/// `interpolate_st` (`v >> 16`) advances one texel per pixel. See ledger R-13. The v2
/// preload plumbing itself is verified (an all-white texture renders white).
#[test]
#[ignore = "WIP: real 1-cycle TEXEL0-pipeline + s10.5 coordinate-scale gaps RustyN64 doesn't model; see ledger R-13"]
fn tex_tri_16_matches_angrylion() {
    assert_matches("tex_tri_16", include_bytes!("vectors/tex_tri_16.rvec"));
}

/// A **COPY-mode Texture Rectangle** (16-bit) — the first texture path validated
/// against Angrylion. Copy mode blits texels straight from TMEM to the colour image
/// (no combiner, no 1-cycle texel pipeline), so it sidesteps the gaps `tex_tri_16`
/// pins. A 4×2 texture (8 byte-asymmetric texels) is preloaded (v2 `.rvec`), loaded
/// by `Load Tile`, and blitted 1:1 (`DsDx = 4.0`, `DtDy = 1.0`) into a 4×2 colour
/// image, so the framebuffer equals the source texels verbatim. Exercises Set Texture
/// Image / Set Tile / Set Tile Size / Load Tile / `texture_rectangle` end-to-end
/// against the oracle (RustyN64 previously only round-trip-tested this internally).
#[test]
fn tex_rect_copy_16_matches_angrylion() {
    assert_matches(
        "tex_rect_copy_16",
        include_bytes!("vectors/tex_rect_copy_16.rvec"),
    );
}

/// A COPY-mode Texture Rectangle blitted to an **offset position** — the same 4×2
/// texture, 1:1-blitted into the (2,2)..(5,3) sub-rectangle of an 8×8 colour image,
/// the rest staying background 0. Exercises the destination positioning (`XH`/`YH`)
/// and the surrounding-pixel/scissor behaviour the origin blit did not.
#[test]
fn tex_rect_offset_16_matches_angrylion() {
    assert_matches(
        "tex_rect_offset_16",
        include_bytes!("vectors/tex_rect_offset_16.rvec"),
    );
}

/// A COPY-mode Texture Rectangle of a full **8×8** texture (64 texels) 1:1-blitted
/// into an 8×8 colour image — exercises the copy load + blit at a larger scale than
/// the small vectors: the full tile stride (`line = 2`), all eight rows, and the
/// odd-row TMEM swap across a bigger surface. The texture is an RGBA5551 gradient.
#[test]
fn tex_rect_8x8_16_matches_angrylion() {
    assert_matches(
        "tex_rect_8x8_16",
        include_bytes!("vectors/tex_rect_8x8_16.rvec"),
    );
}

/// **Alpha-compare** gates the pixel write. A 1-cycle flat-red shaded triangle whose
/// combiner alpha (the interpolated shade alpha) ramps across X (`dx.A = 0x30`), with
/// alpha-compare enabled and a `Set Blend Color` alpha threshold of `0x80`. Columns
/// whose alpha is below the threshold are killed (stay background 0); only the higher-
/// alpha columns draw red. Guards the `alpha_compare_en` write gate.
#[test]
fn alpha_compare_16_matches_angrylion() {
    assert_matches(
        "alpha_compare_16",
        include_bytes!("vectors/alpha_compare_16.rvec"),
    );
}

/// **Alpha-compare on the depth path.** The same shade-alpha ramp + `0x80` threshold
/// as `alpha_compare_16`, but on a z-suffixed triangle (op 0x0D) with `z_update` on
/// and `z_compare` off — so every pixel passes the depth test and alpha-compare is
/// the sole gate. The colour equals the no-Z case (low-alpha columns killed), which
/// guards that `depth_span` applies alpha-compare and skips the killed pixels' write.
#[test]
fn alpha_compare_z_16_matches_angrylion() {
    assert_matches(
        "alpha_compare_z_16",
        include_bytes!("vectors/alpha_compare_z_16.rvec"),
    );
}

/// A **magnified** COPY-mode Texture Rectangle (`DsDx = 2.0`, 0.5 texel/pixel). The
/// RDP copies **4 pixels per cycle**: within a cycle it reads 4 consecutive texels
/// (`base..base+3` from a 64-bit TMEM word) and the base advances by `DsDx × 4`
/// texels per cycle, so an 8-texel ramp magnified 2× reads texels `0,1,2,3,2,3,4,5`
/// (not the naive per-pixel `0,0,1,1,2,2,3,3`). Guards the 4-pixels-per-cycle copy.
#[test]
fn tex_rect_mag_16_matches_angrylion() {
    assert_matches(
        "tex_rect_mag_16",
        include_bytes!("vectors/tex_rect_mag_16.rvec"),
    );
}
