//! The `.rvec` conformance-vector container: parsing and replay.
//!
//! Each `.rvec` vector under `tests/vectors/` is a golden reference generated by
//! running the **Angrylion** software RDP (the non-commercial study oracle, run
//! externally — see `vectors-gen/README.md` for the licence-clean generator) over
//! a fixed RDP command list. The vector carries *only outputs*: the command stream
//! (freely committable) and the golden framebuffer Angrylion rendered — no
//! Angrylion source or binary is vendored, keeping the licence boundary clean.
//!
//! Replaying a vector runs its command stream through `RustyN64`'s own RDP and
//! compares byte-for-byte against that golden. Because the command bytes are
//! stored big-endian (`RustyN64`'s `RDRAM` layout) and the golden pixels are stored as
//! row-major big-endian logical values (exactly what `RustyN64` writes into `RDRAM`),
//! the comparison is a direct byte compare of the framebuffer region.
//!
//! This lives in `src/` rather than the test file so that **both** the conformance
//! test and the [`crate::accuracy`] battery run the same vectors through the same
//! replay — the battery's expected values are Angrylion's, never `RustyN64`'s own
//! output.

#![allow(
    clippy::cast_possible_truncation,
    reason = "vector geometry and command lengths are small, well within u32"
)]

use rustyn64_core::Bus;

/// A parsed `.rvec` conformance vector.
#[derive(Debug)]
pub struct Vector<'a> {
    /// Framebuffer address the command list renders into.
    pub fb_addr: u32,
    /// Framebuffer width in pixels.
    pub width: u32,
    /// Framebuffer height in pixels.
    pub height: u32,
    /// Bytes per pixel (2 = RGBA5551, 4 = RGBA8888).
    pub bpp: u32,
    /// Address the command list is placed at.
    pub cmd_addr: u32,
    /// Address of the optional `RDRAM` preload (a texture a `Load Tile` reads).
    pub preload_addr: u32,
    /// The preload bytes; empty when the vector carries none.
    pub preload: &'a [u8],
    /// The RDP command stream (big-endian words).
    pub cmds: &'a [u8],
    /// The framebuffer Angrylion rendered — the oracle's expected output.
    pub golden_fb: &'a [u8],
}

/// Parse the `.rvec` container.
///
/// The big-endian header is `"RVEC"`, a version, then `fb_addr`, `width`,
/// `height`, `bpp`, `cmd_addr`, `cmd_len`, `fb_len` — **v1** (9 words) stops
/// there; **v2** (11 words) adds `preload_addr`, `preload_len`. The body is the
/// preload bytes (v2 only), then the command bytes, then the golden framebuffer
/// bytes.
///
/// # Panics
///
/// Panics if the container is truncated, carries a bad magic or an unknown
/// version, or declares geometry inconsistent with its payload length.
#[must_use]
pub fn parse(bytes: &[u8]) -> Vector<'_> {
    assert!(
        bytes.len() >= 36,
        "truncated .rvec: shorter than the header"
    );
    let u32_at =
        |i: usize| u32::from_be_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
    assert_eq!(u32_at(0), 0x5256_4543, "bad magic (expected RVEC)");
    let version = u32_at(4);
    assert!(
        version == 1 || version == 2,
        "unexpected vector version {version}"
    );
    let fb_addr = u32_at(8);
    let width = u32_at(12);
    let height = u32_at(16);
    let bpp = u32_at(20);
    let cmd_addr = u32_at(24);
    let cmd_len = u32_at(28) as usize;
    let fb_len = u32_at(32) as usize;
    // v2 carries a preload region (addr + len) in two extra header words.
    let (hdr, preload_addr, preload_len) = if version == 2 {
        assert!(bytes.len() >= 44, "truncated .rvec: v2 header incomplete");
        (44usize, u32_at(36), u32_at(40) as usize)
    } else {
        (36usize, 0u32, 0usize)
    };
    assert!(
        bpp == 2 || bpp == 4,
        "unsupported bpp {bpp} (expected 2 or 4)"
    );
    assert_eq!(
        cmd_len % 4,
        0,
        "command length is not a whole number of words"
    );
    // Checked so an implausible header can't silently wrap the pixel count.
    let expected_fb = (width as usize)
        .checked_mul(height as usize)
        .and_then(|n| n.checked_mul(bpp as usize))
        .expect("framebuffer dimensions overflow");
    assert_eq!(fb_len, expected_fb, "fb_len mismatch");
    let total = hdr
        .checked_add(preload_len)
        .and_then(|n| n.checked_add(cmd_len))
        .and_then(|n| n.checked_add(fb_len))
        .expect("payload sizes overflow");
    assert!(
        bytes.len() >= total,
        "truncated .rvec: header declares more payload than the file holds"
    );
    let preload = &bytes[hdr..hdr + preload_len];
    let cmd_start = hdr + preload_len;
    Vector {
        fb_addr,
        width,
        height,
        bpp,
        cmd_addr,
        preload_addr,
        preload,
        cmds: &bytes[cmd_start..cmd_start + cmd_len],
        golden_fb: &bytes[cmd_start + cmd_len..cmd_start + cmd_len + fb_len],
    }
}

/// Replay `v`'s command stream through `RustyN64`'s RDP.
///
/// Returns the rendered framebuffer region (raw `RDRAM` bytes), which is directly
/// comparable to the golden bytes (both are row-major big-endian logical pixel
/// values).
///
/// # Panics
///
/// Panics if the vector's addresses do not fit in `RDRAM`.
#[must_use]
pub fn replay(v: &Vector<'_>) -> Vec<u8> {
    let mut bus = Bus::new();
    // Load the command list into RDRAM verbatim (big-endian words, as generated).
    let base = v.cmd_addr as usize;
    let fb = v.fb_addr as usize;
    // Widen BEFORE multiplying: `width * height * bpp` in u32 can wrap for a
    // directly-constructed `Vector` (all fields are public), which would silently
    // produce a bogus framebuffer length.
    let fb_len = (v.width as usize) * (v.height as usize) * (v.bpp as usize);
    let pre = v.preload_addr as usize;
    let fits = |start: usize, len: usize| {
        start
            .checked_add(len)
            .is_some_and(|end| end <= bus.rdram.len())
    };
    assert!(
        fits(base, v.cmds.len()) && fits(fb, fb_len) && fits(pre, v.preload.len()),
        "vector addresses exceed RDRAM ({} bytes)",
        bus.rdram.len()
    );
    // Place the optional texture preload (big-endian, RustyN64's RDRAM layout) so a
    // Load Tile in the command list reads it, exactly as the generator placed it in
    // Angrylion's RDRAM before rendering the golden.
    bus.rdram[pre..pre + v.preload.len()].copy_from_slice(v.preload);
    bus.rdram[base..base + v.cmds.len()].copy_from_slice(v.cmds);

    // Point the DP FIFO at the list and drain it (one command per tick).
    bus.rdp.dpc_write(0, v.cmd_addr); // DPC_START
    bus.rdp.dpc_write(1, v.cmd_addr + v.cmds.len() as u32); // DPC_END
    // Drain until the FIFO is OBSERVABLY empty (`DPC_CURRENT >= DPC_END`, the same
    // condition `Rdp::tick` itself no-ops on) rather than for a fitted number of
    // ticks. A tick budget that is merely "generous" can silently score a partly
    // rendered frame as an oracle result; the cap below therefore exists only as a
    // liveness backstop and ASSERTS instead of falling through, so a command that
    // stalls the FIFO (a `Sync Pipe`, say) fails loudly rather than quietly
    // producing a wrong comparison.
    let end = v.cmd_addr.wrapping_add(v.cmds.len() as u32);
    let cap = v.cmds.len() * 8 + 4096;
    let mut ticks = 0usize;
    while bus.rdp.dpc_read(2) < end {
        bus.rdp_tick();
        ticks += 1;
        assert!(
            ticks <= cap,
            "DP FIFO did not drain in {cap} ticks (DPC_CURRENT {:#x} < DPC_END {end:#x}) — \
             the replay would have scored a partly rendered frame",
            bus.rdp.dpc_read(2),
        );
    }

    bus.rdram[fb..fb + fb_len].to_vec()
}

/// Replay a vector and report the first differing pixel, or `None` on a
/// byte-for-byte match with the Angrylion golden.
///
/// # Panics
///
/// Panics if `bytes` is not a well-formed `.rvec` (see [`parse`]).
#[must_use]
pub fn first_mismatch(bytes: &[u8]) -> Option<Mismatch> {
    let v = parse(bytes);
    let got = replay(&v);
    if got == v.golden_fb {
        return None;
    }
    let bpp = v.bpp as usize;
    // Bound by the SHORTER slice: a length mismatch must be reported as such, not
    // indexed past the end of the golden.
    let common = got.len().min(v.golden_fb.len());
    for i in (0..common).step_by(bpp) {
        if got[i..i + bpp] != v.golden_fb[i..i + bpp] {
            let px = (i / bpp) as u32;
            return Some(Mismatch {
                x: px % v.width,
                y: px / v.width,
                got: got[i..i + bpp].to_vec(),
                golden: v.golden_fb[i..i + bpp].to_vec(),
            });
        }
    }
    // Lengths differ without any pixel differing (a truncated replay).
    Some(Mismatch {
        x: 0,
        y: 0,
        got: Vec::new(),
        golden: Vec::new(),
    })
}

/// The first pixel at which a replay diverged from the Angrylion golden.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Mismatch {
    /// Column of the differing pixel.
    pub x: u32,
    /// Row of the differing pixel.
    pub y: u32,
    /// The bytes `RustyN64` rendered (empty when only the lengths differed).
    pub got: Vec<u8>,
    /// The bytes Angrylion rendered (empty when only the lengths differed).
    pub golden: Vec<u8>,
}

/// Every committed RDP conformance vector, as `(name, bytes)`.
///
/// This is the single source of truth for the vector set: the conformance test
/// looks up its vectors here, and the [`crate::accuracy`] battery scores all of
/// them. Adding a vector to this table adds it to both.
pub const RDP_VECTORS: &[(&str, &[u8])] = &[
    (
        "fill_rect_16",
        include_bytes!("../tests/vectors/fill_rect_16.rvec"),
    ),
    (
        "fill_tri_16",
        include_bytes!("../tests/vectors/fill_tri_16.rvec"),
    ),
    (
        "fill_tri_wide_16",
        include_bytes!("../tests/vectors/fill_tri_wide_16.rvec"),
    ),
    (
        "fill_tri_neg_16",
        include_bytes!("../tests/vectors/fill_tri_neg_16.rvec"),
    ),
    (
        "fill_tri_frac_16",
        include_bytes!("../tests/vectors/fill_tri_frac_16.rvec"),
    ),
    (
        "shade_tri_frac_16",
        include_bytes!("../tests/vectors/shade_tri_frac_16.rvec"),
    ),
    (
        "shade_depth_tri_frac_16",
        include_bytes!("../tests/vectors/shade_depth_tri_frac_16.rvec"),
    ),
    (
        "shade_tri_32",
        include_bytes!("../tests/vectors/shade_tri_32.rvec"),
    ),
    (
        "dither_tri_32",
        include_bytes!("../tests/vectors/dither_tri_32.rvec"),
    ),
    (
        "shade_grad_tri_32",
        include_bytes!("../tests/vectors/shade_grad_tri_32.rvec"),
    ),
    (
        "tex_tri_16",
        include_bytes!("../tests/vectors/tex_tri_16.rvec"),
    ),
    (
        "tex_tri_fixed_16",
        include_bytes!("../tests/vectors/tex_tri_fixed_16.rvec"),
    ),
    (
        "tex_rect_copy_16",
        include_bytes!("../tests/vectors/tex_rect_copy_16.rvec"),
    ),
    (
        "tex_rect_offset_16",
        include_bytes!("../tests/vectors/tex_rect_offset_16.rvec"),
    ),
    (
        "tex_rect_8x8_16",
        include_bytes!("../tests/vectors/tex_rect_8x8_16.rvec"),
    ),
    (
        "tex_rect_mag_16",
        include_bytes!("../tests/vectors/tex_rect_mag_16.rvec"),
    ),
    (
        "alpha_compare_16",
        include_bytes!("../tests/vectors/alpha_compare_16.rvec"),
    ),
    (
        "alpha_compare_z_16",
        include_bytes!("../tests/vectors/alpha_compare_z_16.rvec"),
    ),
    (
        "cvg_dest_full_16",
        include_bytes!("../tests/vectors/cvg_dest_full_16.rvec"),
    ),
    (
        "prim_combiner_32",
        include_bytes!("../tests/vectors/prim_combiner_32.rvec"),
    ),
    (
        "tex_tri_i4_16",
        include_bytes!("../tests/vectors/tex_tri_i4_16.rvec"),
    ),
    (
        "tex_tri_clamp_16",
        include_bytes!("../tests/vectors/tex_tri_clamp_16.rvec"),
    ),
    (
        "tex_tri_wrap_16",
        include_bytes!("../tests/vectors/tex_tri_wrap_16.rvec"),
    ),
    (
        "tex_tri_bilinear_16",
        include_bytes!("../tests/vectors/tex_tri_bilinear_16.rvec"),
    ),
    (
        "tex_tri_bilinear_wrap_16",
        include_bytes!("../tests/vectors/tex_tri_bilinear_wrap_16.rvec"),
    ),
    (
        "tex_tri_2cycle_16",
        include_bytes!("../tests/vectors/tex_tri_2cycle_16.rvec"),
    ),
    (
        "tex_tri_primlodfrac_16",
        include_bytes!("../tests/vectors/tex_tri_primlodfrac_16.rvec"),
    ),
    (
        "tex_tri_convert_k45_16",
        include_bytes!("../tests/vectors/tex_tri_convert_k45_16.rvec"),
    ),
    (
        "tex_tri_convert_kneg_16",
        include_bytes!("../tests/vectors/tex_tri_convert_kneg_16.rvec"),
    ),
    (
        "tex_tri_chromakey_16",
        include_bytes!("../tests/vectors/tex_tri_chromakey_16.rvec"),
    ),
    (
        "tex_tri_chromakey_alpha_16",
        include_bytes!("../tests/vectors/tex_tri_chromakey_alpha_16.rvec"),
    ),
    (
        "tex_tri_base_tile_16",
        include_bytes!("../tests/vectors/tex_tri_base_tile_16.rvec"),
    ),
    (
        "tex_tri_mid_texel_16",
        include_bytes!("../tests/vectors/tex_tri_mid_texel_16.rvec"),
    ),
    (
        "tex_tri_lodfrac_16",
        include_bytes!("../tests/vectors/tex_tri_lodfrac_16.rvec"),
    ),
    (
        "tex_tri_mip_tile_16",
        include_bytes!("../tests/vectors/tex_tri_mip_tile_16.rvec"),
    ),
    (
        "fill_rect_1cycle_16",
        include_bytes!("../tests/vectors/fill_rect_1cycle_16.rvec"),
    ),
    (
        "fill_rect_2cycle_16",
        include_bytes!("../tests/vectors/fill_rect_2cycle_16.rvec"),
    ),
    (
        "tex_tri_ci4_tlut_16",
        include_bytes!("../tests/vectors/tex_tri_ci4_tlut_16.rvec"),
    ),
    (
        "load_block_count_16",
        include_bytes!("../tests/vectors/load_block_count_16.rvec"),
    ),
    (
        "ci4_tlut_disabled_16",
        include_bytes!("../tests/vectors/ci4_tlut_disabled_16.rvec"),
    ),
];

/// Look up a committed vector's bytes by name.
///
/// # Panics
///
/// Panics if `name` is not in [`RDP_VECTORS`] — a typo must fail loudly rather
/// than silently skip a vector.
#[must_use]
pub fn vector_bytes(name: &str) -> &'static [u8] {
    RDP_VECTORS
        .iter()
        .find(|(n, _)| *n == name)
        .unwrap_or_else(|| panic!("no committed conformance vector named {name}"))
        .1
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **The vector table is non-empty and every entry parses.** Guards against a
    /// table that silently loses entries (which would make the accuracy battery
    /// quietly score fewer probes).
    #[test]
    fn every_committed_vector_parses() {
        assert!(
            RDP_VECTORS.len() >= 35,
            "the committed vector set shrank unexpectedly: {}",
            RDP_VECTORS.len()
        );
        for (name, bytes) in RDP_VECTORS {
            let v = parse(bytes);
            assert!(v.width > 0 && v.height > 0, "{name}: empty geometry");
            assert!(!v.cmds.is_empty(), "{name}: empty command list");
        }
    }

    /// **Vector names are unique.** A duplicate would double-count in the battery.
    #[test]
    fn vector_names_are_unique() {
        for (i, (name, _)) in RDP_VECTORS.iter().enumerate() {
            assert!(
                !RDP_VECTORS[..i].iter().any(|(n, _)| n == name),
                "duplicate vector name {name}"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// The `.vivec` VI scan-out vectors — the second oracle suite.
// ---------------------------------------------------------------------------

/// A parsed `.vivec` VI scan-out vector (15 big-endian `u32` of header, then the
/// source framebuffer, an optional hidden-bits plane, and the golden output).
#[derive(Debug)]
pub struct ViVector {
    /// `VI_CTRL`.
    pub ctrl: u32,
    /// `VI_ORIGIN` — where the source framebuffer sits in `RDRAM`.
    pub origin: u32,
    /// `VI_WIDTH`.
    pub width: u32,
    /// `VI_X_SCALE`.
    pub x_scale: u32,
    /// `VI_Y_SCALE`.
    pub y_scale: u32,
    /// `VI_H_VIDEO`.
    pub h_video: u32,
    /// `VI_V_VIDEO`.
    pub v_video: u32,
    /// `VI_V_TOTAL`.
    pub v_sync: u32,
    /// Golden output width.
    pub out_w: u32,
    /// Golden output height.
    pub out_h: u32,
    /// Source framebuffer bytes (logical pixels, big-endian — `RustyN64`'s `RDRAM`
    /// order, so they are placed directly at `origin`).
    pub src: Vec<u8>,
    /// The 9th-bit hidden-coverage plane (format version 2 only): one byte per
    /// source pixel, low 2 bits meaningful. `None` for version 1.
    pub hidden: Option<Vec<u8>>,
    /// Golden output, `out_w * out_h` RGBA8 pixels — the oracle's expected frame.
    pub golden: Vec<u8>,
}

/// Parse a `.vivec` container.
///
/// # Panics
///
/// Panics on a bad magic, an unsupported version, an out-of-range `src_bpp`, or a
/// payload shorter than the header declares.
#[must_use]
pub fn parse_vi(bytes: &[u8]) -> ViVector {
    let be_u32 =
        |i: usize| u32::from_be_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
    assert!(bytes.len() >= 15 * 4, "truncated .vivec: header incomplete");
    assert_eq!(be_u32(0), 0x5649_5643, "bad .vivec magic");
    let version = be_u32(4);
    assert!(version == 1 || version == 2, "unsupported .vivec version");
    let h = |i: usize| be_u32(i * 4);
    let (src_w, src_h) = (h(10), h(11));
    let src_bpp = h(12);
    assert!(src_bpp == 2 || src_bpp == 4, "src_bpp must be 2 or 4");
    let (out_w, out_h) = (h(13), h(14));
    // `origin` indexes the hidden-coverage plane as `origin >> 1`, so an odd
    // origin would silently desync that mapping from RDRAM.
    assert_eq!(h(3) % 2, 0, ".vivec origin must be halfword-aligned");
    let mut off: usize = 15 * 4;
    // CHECKED throughout: an implausible header must fail loudly, not wrap `usize`
    // (which would slip past the length check below and panic in a later slice).
    let px = (src_w as usize)
        .checked_mul(src_h as usize)
        .expect("source dimensions overflow");
    let src_len = px
        .checked_mul(src_bpp as usize)
        .expect("source length overflows");
    let hidden_len = if version == 2 { px } else { 0 };
    let golden_len = (out_w as usize)
        .checked_mul(out_h as usize)
        .and_then(|n| n.checked_mul(4))
        .expect("golden dimensions overflow");
    let total = off
        .checked_add(src_len)
        .and_then(|n| n.checked_add(hidden_len))
        .and_then(|n| n.checked_add(golden_len))
        .expect("payload sizes overflow");
    assert!(
        bytes.len() >= total,
        "truncated .vivec: header declares more payload than the file holds"
    );
    let src = bytes[off..off + src_len].to_vec();
    off += src_len;
    let hidden = (version == 2).then(|| {
        let plane = bytes[off..off + hidden_len].to_vec();
        off += hidden_len;
        plane
    });
    let golden = bytes[off..off + golden_len].to_vec();
    ViVector {
        ctrl: h(2),
        origin: h(3),
        width: h(4),
        x_scale: h(5),
        y_scale: h(6),
        h_video: h(7),
        v_video: h(8),
        v_sync: h(9),
        out_w,
        out_h,
        src,
        hidden,
        golden,
    }
}

/// Scan `v` out through `RustyN64`'s VI and return `(dims, rgba_frame)`.
///
/// Places the source framebuffer big-endian at `origin`, packs the optional
/// hidden-coverage plane into the bus's hidden-bits store at the halfword indices
/// the VI reads, programs the VI registers through the CPU MMIO path, and runs
/// [`Bus::scanout_scaled`].
///
/// # Panics
///
/// Panics if the source framebuffer does not fit in `RDRAM`.
#[must_use]
pub fn replay_vi(v: &ViVector) -> ((u32, u32), Vec<u8>) {
    use rustyn64_core::cpu::Bus as CpuBus;
    const VI: u32 = 0x0440_0000; // VI register block base

    let mut bus = Bus::new();
    let base = v.origin as usize;
    assert!(
        base.checked_add(v.src.len())
            .is_some_and(|end| end <= bus.rdram.len()),
        "source framebuffer exceeds RDRAM"
    );
    bus.rdram[base..base + v.src.len()].copy_from_slice(&v.src);

    // Source pixel (x, y) is the contiguous halfword `(origin >> 1) + y*src_w + x`;
    // the store packs 2 bits per halfword, 4 halfwords to a byte.
    if let Some(hidden) = &v.hidden {
        let mut plane = vec![0u8; bus.rdram.len() / 8];
        let hw0 = base >> 1; // origin is halfword-aligned
        for (i, &hv) in hidden.iter().enumerate() {
            let hw = hw0 + i;
            let shift = (hw & 3) * 2;
            plane[hw >> 2] |= (hv & 0x3) << shift;
        }
        bus.rdram_hidden = Some(plane.into_boxed_slice());
    }

    CpuBus::write_u32(&mut bus, VI, v.ctrl); // VI_CTRL    (+0x00)
    CpuBus::write_u32(&mut bus, VI + 0x04, v.origin); // VI_ORIGIN  (+0x04)
    CpuBus::write_u32(&mut bus, VI + 0x08, v.width); // VI_WIDTH   (+0x08)
    CpuBus::write_u32(&mut bus, VI + 0x18, v.v_sync); // VI_V_TOTAL (+0x18)
    CpuBus::write_u32(&mut bus, VI + 0x24, v.h_video); // VI_H_VIDEO (+0x24)
    CpuBus::write_u32(&mut bus, VI + 0x28, v.v_video); // VI_V_VIDEO (+0x28)
    CpuBus::write_u32(&mut bus, VI + 0x30, v.x_scale); // VI_X_SCALE (+0x30)
    CpuBus::write_u32(&mut bus, VI + 0x34, v.y_scale); // VI_Y_SCALE (+0x34)

    // Checked: `ViVector` is public, so `replay_vi` must validate independently of
    // `parse_vi` rather than trusting a hand-built value.
    let frame_len = (v.out_w as usize)
        .checked_mul(v.out_h as usize)
        .and_then(|n| n.checked_mul(4))
        .expect("output dimensions overflow");
    let mut frame = vec![0u8; frame_len];
    let dims = bus.scanout_scaled(&mut frame);
    (dims, frame)
}

/// Where a VI scan-out diverged from the Angrylion golden.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ViMismatch {
    /// The scan-out geometry itself differed.
    Geometry {
        /// The dimensions `RustyN64` produced.
        got: (u32, u32),
        /// The dimensions the oracle produced.
        golden: (u32, u32),
    },
    /// An RGB pixel differed.
    Pixel {
        /// Column of the differing pixel.
        x: u32,
        /// Row of the differing pixel.
        y: u32,
        /// The RGB bytes `RustyN64` produced.
        got: Vec<u8>,
        /// The RGB bytes the oracle produced.
        golden: Vec<u8>,
    },
}

/// Scan a `.vivec` out and report the first divergence from the Angrylion golden,
/// or `None` on a match.
///
/// **Scope: RGB only.** The fourth byte of each output pixel carries Angrylion's
/// *coverage*, not opacity, so it is deliberately excluded — an alpha-only
/// divergence does NOT fail this comparison. The RDP `.rvec` comparison
/// ([`first_mismatch`]) is byte-for-byte; this one is not, and every label that
/// reports it says so.
///
/// # Panics
///
/// Panics if `bytes` is not a well-formed `.vivec` (see [`parse_vi`]).
#[must_use]
pub fn vi_first_mismatch(bytes: &[u8]) -> Option<ViMismatch> {
    let v = parse_vi(bytes);
    let (dims, frame) = replay_vi(&v);
    if dims != (v.out_w, v.out_h) {
        return Some(ViMismatch::Geometry {
            got: dims,
            golden: (v.out_w, v.out_h),
        });
    }
    for y in 0..v.out_h {
        for x in 0..v.out_w {
            let i = ((y * v.out_w + x) * 4) as usize;
            if frame[i..i + 3] != v.golden[i..i + 3] {
                return Some(ViMismatch::Pixel {
                    x,
                    y,
                    got: frame[i..i + 3].to_vec(),
                    golden: v.golden[i..i + 3].to_vec(),
                });
            }
        }
    }
    None
}

/// Every committed VI scan-out conformance vector, as `(name, bytes)`.
///
/// The counterpart to [`RDP_VECTORS`] for the VI pipeline; the [`crate::accuracy`]
/// battery scores both.
pub const VI_VECTORS: &[(&str, &[u8])] = &[
    (
        "vi_scale_1x_16",
        include_bytes!("../tests/vectors/vi_scale_1x_16.vivec"),
    ),
    (
        "vi_scale_down2x_16",
        include_bytes!("../tests/vectors/vi_scale_down2x_16.vivec"),
    ),
    (
        "vi_scale_bilinear_16",
        include_bytes!("../tests/vectors/vi_scale_bilinear_16.vivec"),
    ),
    (
        "vi_scale_bilinear_odd_16",
        include_bytes!("../tests/vectors/vi_scale_bilinear_odd_16.vivec"),
    ),
    (
        "vi_gamma_1x_16",
        include_bytes!("../tests/vectors/vi_gamma_1x_16.vivec"),
    ),
    (
        "vi_pal_geometry_16",
        include_bytes!("../tests/vectors/vi_pal_geometry_16.vivec"),
    ),
    (
        "vi_scale_bilinear_32",
        include_bytes!("../tests/vectors/vi_scale_bilinear_32.vivec"),
    ),
    (
        "vi_dedither_32",
        include_bytes!("../tests/vectors/vi_dedither_32.vivec"),
    ),
    (
        "vi_aa_edge_32",
        include_bytes!("../tests/vectors/vi_aa_edge_32.vivec"),
    ),
    (
        "vi_divot_32",
        include_bytes!("../tests/vectors/vi_divot_32.vivec"),
    ),
    (
        "vi_dedither_16",
        include_bytes!("../tests/vectors/vi_dedither_16.vivec"),
    ),
    (
        "vi_aa_edge_16",
        include_bytes!("../tests/vectors/vi_aa_edge_16.vivec"),
    ),
    (
        "vi_divot_16",
        include_bytes!("../tests/vectors/vi_divot_16.vivec"),
    ),
];

/// Look up a committed VI vector's bytes by name.
///
/// # Panics
///
/// Panics if `name` is not in [`VI_VECTORS`] — a typo must fail loudly rather than
/// silently skip a vector.
#[must_use]
pub fn vi_vector_bytes(name: &str) -> &'static [u8] {
    VI_VECTORS
        .iter()
        .find(|(n, _)| *n == name)
        .unwrap_or_else(|| panic!("no committed VI conformance vector named {name}"))
        .1
}
