//! The `.rvec` conformance-vector container: parsing and replay.
//!
//! Each `.rvec` vector under `tests/vectors/` is a golden reference generated by
//! running the **Angrylion** software RDP (the non-commercial study oracle, run
//! externally — see `vectors-gen/README.md` for the licence-clean generator) over
//! a fixed RDP command list. The vector carries *only outputs*: the command stream
//! (freely committable) and the golden framebuffer Angrylion rendered — no
//! Angrylion source or binary is vendored, keeping the licence boundary clean.
//!
//! Replaying a vector runs its command stream through `RustyN64`'s own RDP and
//! compares byte-for-byte against that golden. Because the command bytes are
//! stored big-endian (`RustyN64`'s `RDRAM` layout) and the golden pixels are stored as
//! row-major big-endian logical values (exactly what `RustyN64` writes into `RDRAM`),
//! the comparison is a direct byte compare of the framebuffer region.
//!
//! This lives in `src/` rather than the test file so that **both** the conformance
//! test and the [`crate::accuracy`] battery run the same vectors through the same
//! replay — the battery's expected values are Angrylion's, never `RustyN64`'s own
//! output.

#![allow(
    clippy::cast_possible_truncation,
    reason = "vector geometry and command lengths are small, well within u32"
)]

use rustyn64_core::Bus;

/// A parsed `.rvec` conformance vector.
#[derive(Debug)]
pub struct Vector<'a> {
    /// Framebuffer address the command list renders into.
    pub fb_addr: u32,
    /// Framebuffer width in pixels.
    pub width: u32,
    /// Framebuffer height in pixels.
    pub height: u32,
    /// Bytes per pixel (2 = RGBA5551, 4 = RGBA8888).
    pub bpp: u32,
    /// Address the command list is placed at.
    pub cmd_addr: u32,
    /// Address of the optional `RDRAM` preload (a texture a `Load Tile` reads).
    pub preload_addr: u32,
    /// The preload bytes; empty when the vector carries none.
    pub preload: &'a [u8],
    /// The RDP command stream (big-endian words).
    pub cmds: &'a [u8],
    /// The framebuffer Angrylion rendered — the oracle's expected output.
    pub golden_fb: &'a [u8],
}

/// Parse the `.rvec` container.
///
/// The big-endian header is `"RVEC"`, a version, then `fb_addr`, `width`,
/// `height`, `bpp`, `cmd_addr`, `cmd_len`, `fb_len` — **v1** (9 words) stops
/// there; **v2** (11 words) adds `preload_addr`, `preload_len`. The body is the
/// preload bytes (v2 only), then the command bytes, then the golden framebuffer
/// bytes.
///
/// # Panics
///
/// Panics if the container is truncated, carries a bad magic or an unknown
/// version, or declares geometry inconsistent with its payload length.
#[must_use]
pub fn parse(bytes: &[u8]) -> Vector<'_> {
    assert!(
        bytes.len() >= 36,
        "truncated .rvec: shorter than the header"
    );
    let u32_at =
        |i: usize| u32::from_be_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
    assert_eq!(u32_at(0), 0x5256_4543, "bad magic (expected RVEC)");
    let version = u32_at(4);
    assert!(
        version == 1 || version == 2,
        "unexpected vector version {version}"
    );
    let fb_addr = u32_at(8);
    let width = u32_at(12);
    let height = u32_at(16);
    let bpp = u32_at(20);
    let cmd_addr = u32_at(24);
    let cmd_len = u32_at(28) as usize;
    let fb_len = u32_at(32) as usize;
    // v2 carries a preload region (addr + len) in two extra header words.
    let (hdr, preload_addr, preload_len) = if version == 2 {
        assert!(bytes.len() >= 44, "truncated .rvec: v2 header incomplete");
        (44usize, u32_at(36), u32_at(40) as usize)
    } else {
        (36usize, 0u32, 0usize)
    };
    assert!(
        bpp == 2 || bpp == 4,
        "unsupported bpp {bpp} (expected 2 or 4)"
    );
    assert_eq!(
        cmd_len % 4,
        0,
        "command length is not a whole number of words"
    );
    // Checked so an implausible header can't silently wrap the pixel count.
    let expected_fb = (width as usize)
        .checked_mul(height as usize)
        .and_then(|n| n.checked_mul(bpp as usize))
        .expect("framebuffer dimensions overflow");
    assert_eq!(fb_len, expected_fb, "fb_len mismatch");
    let total = hdr
        .checked_add(preload_len)
        .and_then(|n| n.checked_add(cmd_len))
        .and_then(|n| n.checked_add(fb_len))
        .expect("payload sizes overflow");
    assert!(
        bytes.len() >= total,
        "truncated .rvec: header declares more payload than the file holds"
    );
    let preload = &bytes[hdr..hdr + preload_len];
    let cmd_start = hdr + preload_len;
    Vector {
        fb_addr,
        width,
        height,
        bpp,
        cmd_addr,
        preload_addr,
        preload,
        cmds: &bytes[cmd_start..cmd_start + cmd_len],
        golden_fb: &bytes[cmd_start + cmd_len..cmd_start + cmd_len + fb_len],
    }
}

/// Replay `v`'s command stream through `RustyN64`'s RDP.
///
/// Returns the rendered framebuffer region (raw `RDRAM` bytes), which is directly
/// comparable to the golden bytes (both are row-major big-endian logical pixel
/// values).
///
/// # Panics
///
/// Panics if the vector's addresses do not fit in `RDRAM`.
#[must_use]
pub fn replay(v: &Vector<'_>) -> Vec<u8> {
    let mut bus = Bus::new();
    // Load the command list into RDRAM verbatim (big-endian words, as generated).
    let base = v.cmd_addr as usize;
    let fb = v.fb_addr as usize;
    let fb_len = (v.width * v.height * v.bpp) as usize;
    let pre = v.preload_addr as usize;
    assert!(
        base + v.cmds.len() <= bus.rdram.len()
            && fb + fb_len <= bus.rdram.len()
            && pre + v.preload.len() <= bus.rdram.len(),
        "vector addresses exceed RDRAM ({} bytes)",
        bus.rdram.len()
    );
    // Place the optional texture preload (big-endian, RustyN64's RDRAM layout) so a
    // Load Tile in the command list reads it, exactly as the generator placed it in
    // Angrylion's RDRAM before rendering the golden.
    bus.rdram[pre..pre + v.preload.len()].copy_from_slice(v.preload);
    bus.rdram[base..base + v.cmds.len()].copy_from_slice(v.cmds);

    // Point the DP FIFO at the list and drain it (one command per tick).
    bus.rdp.dpc_write(0, v.cmd_addr); // DPC_START
    bus.rdp.dpc_write(1, v.cmd_addr + v.cmds.len() as u32); // DPC_END
    let n_words = v.cmds.len() / 4;
    // A generous budget: multi-word triangle commands still retire in a handful
    // of ticks, so twice the word count cannot leave the FIFO mid-list.
    for _ in 0..(n_words * 2 + 16) {
        bus.rdp_tick();
    }

    bus.rdram[fb..fb + fb_len].to_vec()
}

/// Replay a vector and report the first differing pixel, or `None` on a
/// byte-for-byte match with the Angrylion golden.
///
/// # Panics
///
/// Panics if `bytes` is not a well-formed `.rvec` (see [`parse`]).
#[must_use]
pub fn first_mismatch(bytes: &[u8]) -> Option<Mismatch> {
    let v = parse(bytes);
    let got = replay(&v);
    if got == v.golden_fb {
        return None;
    }
    let bpp = v.bpp as usize;
    for i in (0..got.len()).step_by(bpp) {
        if got[i..i + bpp] != v.golden_fb[i..i + bpp] {
            let px = (i / bpp) as u32;
            return Some(Mismatch {
                x: px % v.width,
                y: px / v.width,
                got: got[i..i + bpp].to_vec(),
                golden: v.golden_fb[i..i + bpp].to_vec(),
            });
        }
    }
    // Lengths differ without any pixel differing (a truncated replay).
    Some(Mismatch {
        x: 0,
        y: 0,
        got: Vec::new(),
        golden: Vec::new(),
    })
}

/// The first pixel at which a replay diverged from the Angrylion golden.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Mismatch {
    /// Column of the differing pixel.
    pub x: u32,
    /// Row of the differing pixel.
    pub y: u32,
    /// The bytes `RustyN64` rendered (empty when only the lengths differed).
    pub got: Vec<u8>,
    /// The bytes Angrylion rendered (empty when only the lengths differed).
    pub golden: Vec<u8>,
}

/// Every committed RDP conformance vector, as `(name, bytes)`.
///
/// This is the single source of truth for the vector set: the conformance test
/// looks up its vectors here, and the [`crate::accuracy`] battery scores all of
/// them. Adding a vector to this table adds it to both.
pub const RDP_VECTORS: &[(&str, &[u8])] = &[
    (
        "fill_rect_16",
        include_bytes!("../tests/vectors/fill_rect_16.rvec"),
    ),
    (
        "fill_tri_16",
        include_bytes!("../tests/vectors/fill_tri_16.rvec"),
    ),
    (
        "fill_tri_wide_16",
        include_bytes!("../tests/vectors/fill_tri_wide_16.rvec"),
    ),
    (
        "fill_tri_neg_16",
        include_bytes!("../tests/vectors/fill_tri_neg_16.rvec"),
    ),
    (
        "fill_tri_frac_16",
        include_bytes!("../tests/vectors/fill_tri_frac_16.rvec"),
    ),
    (
        "shade_tri_frac_16",
        include_bytes!("../tests/vectors/shade_tri_frac_16.rvec"),
    ),
    (
        "shade_depth_tri_frac_16",
        include_bytes!("../tests/vectors/shade_depth_tri_frac_16.rvec"),
    ),
    (
        "shade_tri_32",
        include_bytes!("../tests/vectors/shade_tri_32.rvec"),
    ),
    (
        "dither_tri_32",
        include_bytes!("../tests/vectors/dither_tri_32.rvec"),
    ),
    (
        "shade_grad_tri_32",
        include_bytes!("../tests/vectors/shade_grad_tri_32.rvec"),
    ),
    (
        "tex_tri_16",
        include_bytes!("../tests/vectors/tex_tri_16.rvec"),
    ),
    (
        "tex_tri_fixed_16",
        include_bytes!("../tests/vectors/tex_tri_fixed_16.rvec"),
    ),
    (
        "tex_rect_copy_16",
        include_bytes!("../tests/vectors/tex_rect_copy_16.rvec"),
    ),
    (
        "tex_rect_offset_16",
        include_bytes!("../tests/vectors/tex_rect_offset_16.rvec"),
    ),
    (
        "tex_rect_8x8_16",
        include_bytes!("../tests/vectors/tex_rect_8x8_16.rvec"),
    ),
    (
        "tex_rect_mag_16",
        include_bytes!("../tests/vectors/tex_rect_mag_16.rvec"),
    ),
    (
        "alpha_compare_16",
        include_bytes!("../tests/vectors/alpha_compare_16.rvec"),
    ),
    (
        "alpha_compare_z_16",
        include_bytes!("../tests/vectors/alpha_compare_z_16.rvec"),
    ),
    (
        "cvg_dest_full_16",
        include_bytes!("../tests/vectors/cvg_dest_full_16.rvec"),
    ),
    (
        "prim_combiner_32",
        include_bytes!("../tests/vectors/prim_combiner_32.rvec"),
    ),
    (
        "tex_tri_i4_16",
        include_bytes!("../tests/vectors/tex_tri_i4_16.rvec"),
    ),
    (
        "tex_tri_clamp_16",
        include_bytes!("../tests/vectors/tex_tri_clamp_16.rvec"),
    ),
    (
        "tex_tri_wrap_16",
        include_bytes!("../tests/vectors/tex_tri_wrap_16.rvec"),
    ),
    (
        "tex_tri_bilinear_16",
        include_bytes!("../tests/vectors/tex_tri_bilinear_16.rvec"),
    ),
    (
        "tex_tri_bilinear_wrap_16",
        include_bytes!("../tests/vectors/tex_tri_bilinear_wrap_16.rvec"),
    ),
    (
        "tex_tri_2cycle_16",
        include_bytes!("../tests/vectors/tex_tri_2cycle_16.rvec"),
    ),
    (
        "tex_tri_primlodfrac_16",
        include_bytes!("../tests/vectors/tex_tri_primlodfrac_16.rvec"),
    ),
    (
        "tex_tri_convert_k45_16",
        include_bytes!("../tests/vectors/tex_tri_convert_k45_16.rvec"),
    ),
    (
        "tex_tri_convert_kneg_16",
        include_bytes!("../tests/vectors/tex_tri_convert_kneg_16.rvec"),
    ),
    (
        "tex_tri_chromakey_16",
        include_bytes!("../tests/vectors/tex_tri_chromakey_16.rvec"),
    ),
    (
        "tex_tri_chromakey_alpha_16",
        include_bytes!("../tests/vectors/tex_tri_chromakey_alpha_16.rvec"),
    ),
    (
        "tex_tri_base_tile_16",
        include_bytes!("../tests/vectors/tex_tri_base_tile_16.rvec"),
    ),
    (
        "tex_tri_mid_texel_16",
        include_bytes!("../tests/vectors/tex_tri_mid_texel_16.rvec"),
    ),
    (
        "tex_tri_lodfrac_16",
        include_bytes!("../tests/vectors/tex_tri_lodfrac_16.rvec"),
    ),
    (
        "tex_tri_mip_tile_16",
        include_bytes!("../tests/vectors/tex_tri_mip_tile_16.rvec"),
    ),
];

/// Look up a committed vector's bytes by name.
///
/// # Panics
///
/// Panics if `name` is not in [`RDP_VECTORS`] — a typo must fail loudly rather
/// than silently skip a vector.
#[must_use]
pub fn vector_bytes(name: &str) -> &'static [u8] {
    RDP_VECTORS
        .iter()
        .find(|(n, _)| *n == name)
        .unwrap_or_else(|| panic!("no committed conformance vector named {name}"))
        .1
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **The vector table is non-empty and every entry parses.** Guards against a
    /// table that silently loses entries (which would make the accuracy battery
    /// quietly score fewer probes).
    #[test]
    fn every_committed_vector_parses() {
        assert!(
            RDP_VECTORS.len() >= 35,
            "the committed vector set shrank unexpectedly: {}",
            RDP_VECTORS.len()
        );
        for (name, bytes) in RDP_VECTORS {
            let v = parse(bytes);
            assert!(v.width > 0 && v.height > 0, "{name}: empty geometry");
            assert!(!v.cmds.is_empty(), "{name}: empty command list");
        }
    }

    /// **Vector names are unique.** A duplicate would double-count in the battery.
    #[test]
    fn vector_names_are_unique() {
        for (i, (name, _)) in RDP_VECTORS.iter().enumerate() {
            assert!(
                !RDP_VECTORS[..i].iter().any(|(n, _)| n == name),
                "duplicate vector name {name}"
            );
        }
    }
}
